import React, { useEffect, useState } from "react";
import "./tc.css";

export default function TermsPage() {
  const [showScrollTop, setShowScrollTop] = useState(false);

  useEffect(() => {
    const onScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="tc-container">
      {/* Header */}
      {/* <div className="tc-title">ConsultCraft LLC</div> */}
      <div className="tc-updated">Terms of Use</div>

      {/* Content */}
      <div className="tc-content">
                  <p>
            1. OWNERSHIP OF SITE AND APP; AGREEMENT TO TERMS OF USE These Terms and Conditions of Use (the “Terms of Use”, "Agreement") apply to all ConsultCraft LLC web sites, including without limitation, those located at www.consultcraftinc.com and www.consultcove.com, and all associated sites linked to www.consultcraftinc.com by ConsultCraft LLC, its parent and subsidiaries, affiliates and related entities (the “Site”). The Site is the property of ConsultCraft LLC. BY USING THE SITE, YOU AGREE TO THESE TERMS OF USE; IF YOU DO NOT AGREE, DO NOT USE THE SITE.
          </p>

          <p>
            These Terms and Conditions also govern your access to and use of the SportsCove mobile application ("App", "Service") operated by ConsultCraft Inc.("Company", "we", "us", "our"). The App is available for download on mobile platforms including iOS and Android.
          </p>

          <p>
            BY DOWNLOADING, INSTALLING, ACCESSING, OR USING THE SPORTSCOVE APP, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT USE THE APP.
          </p>

          <p>2. COPYRIGHT NOTICE</p>

          <p>
            This Site is the official Site of ConsultCraft, LLC and is © 2025 Copyright ConsultCraft LLC. Commercial reproduction, distribution or transmission of any part or parts of this website or any information contained therein by any means whatsoever without the prior written permission of the ConsultCraft, LLC is not permitted.
          </p>

          <p>
            “SportsCove,” “ConsultCove,” “SportsCoveTribe,” are registered trademarks, trademarks, trade dress or service marks owned exclusively by ConsultCraft, LLC in the United States and other jurisdictions. All other marks referenced herein may be the property of ConsultCraft, LLC or other respective owners.
          </p>

          <p>1. BACKGROUND</p>

          <p>
            1.1 This document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the rules framed there under as applicable; and (iii) the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p>
            1.2 This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that requires publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of [www.consultcraftinc.com] website (“Website”) and the application called SportsCove (“Application”). For the purposes of this Terms of Use document, the terms of the Website and Application shall be collectively referred to as “Platform”.
          </p>

          <p>
            1.3 The Platform is owned, registered and operated by ConsultCraft LLC, a Limited Liability Company registered/incorporated under the provisions of the laws of Delaware, USA and having its registered office at 4520 W OAKELLAR AVENUE, 13348, TAMPA, FL, 33611 (“Company”).
          </p>

          <p>
            1.4 These terms of usage (“Terms of Use”) govern your use of the Platform and Services (as defined below) provided through the Platform. By using or visiting the Platform you shall be deemed to have read, understood and accepted to be bound by these Terms of Use.
          </p>

          <p>
            1.5 For the purpose of these Terms of Use, wherever the context so requires "You", “Your” or “User” shall mean any natural or legal person who uses the Platform for availing the Services. The term “We”, “Us”, “Our” shall mean the Company.
          </p>

          <p>
            1.6 We reserve the right to make changes to these Terms of Use at any time. Any such modifications will become effective immediately upon posting on the Platform and your continued use of the Platform, and/or the Services constitutes your agreement to such modifications. You agree to periodically review the current version of these Terms of Use as posted on the Platform.
          </p>

          <p>2. SERVICES</p>

          <p>2.1 Description</p>

          <p>
            Through our Platform, We provide online fitness programs, transformation and home workout as well as nutrition plans for overall wellbeing to Our Users, which include – (i) online sessions/subscriptions permitting access to and booking pre-recorded audio/video content relating to physical and/or mental fitness, nutrition, recreation and allied content; and (ii) sessions/subscriptions from relevant partners (onboarded by the Company) permitting access to booking of real-time audio and/or video consultancy/coaching and/or training sessions relating to physical and/or mental and/or holistic fitness and/or wellness, nutrition or recreation (hereinafter collectively referred to as “Services”).
          </p>

          <p>
            The specific terms and conditions with respect to the various packages of Services offered by the Company may be accessed here.
          </p>

          <p>2.2 Registration</p>

          <p>
            2.2.1 Access to and use of the Platform is restricted to registered Users only. Some content on the Platform may require different types of registrations and/or payment of additional fees. In order to register and use the Platform, You must provide truthful and accurate account information, including but not limited to username, email address, phone number, billing address, and credit card information. You are responsible for updating Your account information as necessary to keep it accurate. Failure to maintain accurate account information could limit Your access to the Platform.
          </p>

          <p>
            2.2.2 You are required to register/ purchase the Services through the Platform. You may download and use the Application and/or the Website through the username and the password assigned to You. The Platform is exclusively made available for the registered users.
          </p>

          <p>
            2.2.3 You are solely responsible for maintaining the confidentiality of Your account, and password and for all activities and liabilities associated with or occurring under Your account, and password.
          </p>

          <p>
            2.2.4 In the event that You find that You are a victim of identity theft, and someone is using Your name/personal details to make use of Our Services, You should immediately notify us on sc-support@consultcraftinc.com. We reserve the right to suspend any account at any time with or without notification to the Users in order to prevent any occurrence of what We believe to be a fraudulent activity.
          </p>

          <p>
            2.2.5 You agree to: (a) maintain and promptly update information to keep it true, accurate, current and complete; and (b) use the Platform only to avail the Services in accordance with the terms and conditions stipulated in this Terms of Use document, and such other guidelines as may be notified by the Company from time to time.
          </p>

          <p>2.3 Usage of the Platform</p>

          <p>
            2.3.1 Subject to compliance with the Terms of Use document, the Company grants You a non-exclusive, revocable, limited privilege to access and use this Platform and the Platform Services. You agree to use the Platform Services, Platform and the materials provided therein only: (a) for purposes that are permitted by the Terms of Use; (b) for purposes for which the Platform Services are meant to be used; and (c) in accordance with any applicable law, regulation or generally accepted practices or guidelines. You agree not to engage in activities that may adversely affect the use of the Platform by the Company/other Users.
          </p>

          <p>
            2.3.2 You agree not to access (or attempt to access) the Platform and the materials or Platform Services by any means other than through the interface that is provided by the Company. You shall not use any deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or Content (as defined below), or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials or any Content, to obtain or attempt to obtain any materials, bookings, documents or information through any means not specifically made available through the Platform.
          </p>

          <p>
            2.3.3 Every User must use his/her own account to avail the Services made available through the Platform. The Platform Content shall be made available to the User only for the duration of the program subscribed by the User. Premium features like marketplace access shall be blocked/restricted upon the completion/expiry of the duration of the subscribed program.
          </p>

          <p>
            2.3.4 The commencement of the subscribed program shall be as per the dates chosen by You at the time of purchasing the program.
          </p>

          <p>
            2.3.5 In the event You pause/go off the subscribed program at any point in time during the subscribed period, You will have the option to rejoin and continue the program at any point in time during the subscribed period either: (i) from the date on which you decide to rejoin the program; OR (ii) from the date on which you had paused the program. However, please note that the total duration of the subscribed program OR the end date of the said program as indicated at the time of subscription shall not be extended from the date You rejoin the program .
          </p>

          <p>
            2.3.6 You acknowledge and agree that by accessing or using the Platform or Platform Services or Content, You may be exposed to content from others that You may consider offensive, indecent or otherwise objectionable. The Company disclaims all liabilities arising in relation to such offensive content on the Platform.
          </p>

          <p>
            2.3.7 If the Platform allows You to post and upload any material on the Platform, You hereby undertake to ensure that such material is not offensive and is in accordance with applicable laws. All material added, created, uploaded, submitted, distributed, or posted to the Platform by You is Your sole responsibility. The Company reserves the right to review any information provided/data uploaded, if any, by You on the Platform and delete any information/data that is inconsistent with these Terms of Use.
          </p>

          <p>
            2.3.8 Except as expressly indicated herein, the Company hereby grants You a non-exclusive, freely revocable, non-transferable access to view any Content available on the Platform, subject to the following conditions: (a) You may access the Content solely for personal, informational, and internal purposes, in accordance with the Terms of Use; (b) You may not modify or alter the Content available on the Platform; (c) You may not distribute or sell, rent, lease, license or otherwise make any Content on the Platform available to others; and (d) You may not remove any text, copyright or other proprietary notices contained in the Content downloaded from the Platform.
          </p>

          <p>2.4 Eligibility to Use the Platform</p>

          <p>
            2.4.1 The Platform Services are not available to minors i.e., persons under the age of 18 (eighteen) years or to any Users suspended or removed by the Company for any reason whatsoever. You represent that You are of legal age to form a binding contract and are not a person barred from receiving Platform Services under the applicable laws.
          </p>

          <p>
            2.4.2 The Company reserves the right to refuse access to the Platform or Platform Services to new Users or to terminate access granted to existing User(s) at any time without according any reasons for doing so.
          </p>

          <p>
            2.4.3 You shall not have more than one active Account (as defined hereinafter) on the Platform. Additionally, You are prohibited from selling, trading, or otherwise transferring Your Account to another party or impersonating any other person for the purposing of creating an account with the Platform.
          </p>

          <p>
            2.4.4 You shall not share the password of Your Account, share or transfer Your Account with any other person. We reserve the right to terminate your subscription/registration hereunder if We, in Our sole and absolute discretion, believe that You are in violation of this Clause 2.4.4 and Clause 2.4.3 above. Also, please note that in the event Your subscription to a program is terminated pursuant to this Clause 2.4.4, the subscription fees paid by You to the Company shall not be refundable.
          </p>

          <p>2.5 Modification of Services</p>

          <p>
            We reserve the right to add, change or remove features and other aspects of the Services provided under these Terms of Use. These Terms of Use shall continue to apply to such modified Services. We further reserve the right to, at any time, and from time to time, modify, discontinue, temporarily or permanently, the Platform or the Services provided, or any part thereof, with or without notice to You. It is hereby agreed by You that You shall not hold the Company liable for any such modification, temporary suspension or discontinuation of the Platform or the Services.
          </p>

          <p>3. SUBSCRIPTION FEES, PAYMENT TERMS AND REFUND POLICY</p>

          <p>
            3.1. The fees charged for accessing the Platform shall be referred to as “Subscription Fees”. You shall be required to submit payment in advance to access the Platform. Payment of Subscription Fees shall be conducted automatically. If payment of a Subscription Fee is not successful for any reason, Your access to the Platform shall be suspended until the payment is realized in Our account. If We are unable to effect automatic payment via your credit card or through any other authorized mode of payment made available through the Platform, We will attempt to notify You via email. Since the Platform is delivered in full at the beginning of the subscription period, the amounts paid for Platform subscription shall not be refundable.
          </p>

          <p>
            3.2. We shall publish a Subscription Fee schedule on the Platform for your review. These Subscription Fees shall be subject to change from time to time at Our sole discretion and We shall use good faith efforts to notify you via email or such other means (as may be viable to Us) prior to effectuating a change to the fee schedule.
          </p>

          <p>
            3.3. As a condition for using the Platform, You shall be required to make the requisite payment of the applicable Subscription Fees. Payment for the Platform must be made via an online transfer/net banking or via Your debit card or credit card to the Company’s designated bank account. Other forms of payment, including cash, cheque and demand draft shall not be acceptable. You shall be solely responsible for paying the Subscription Fees billed through your credit card or online transfers for the Subscription Fees. All Subscription Fees shall be payable in Indian Rupees (INR) only. Any payments made via credit card are subject to the approval of the financial institution that issued the credit card. The transaction fee for making the payments through debit/credit cards/ net banking/ online transfer shall be borne by You.
          </p>

          <p>
            3.4. As mentioned above, all Our Services are digital, they are deemed "used" on purchase. This means that We have a strict no refund policy with regard to any dissatisfaction that You may have with respect to the Services availed through the Platform. You may contact sc-support@consultcraftinc.com to share any queries/concerns that you may have with our Services. Notwithstanding anything contained in this Clause 3.4, the approval of any refund requests shall be solely subject to the discretion of the Company.
          </p>

          <p>
            3.5. You understand, accept and agree that the payment facility provided on the Platform is neither a banking nor financial service but is merely a facilitator providing an an automated online electronic payment, collection and remittance facility for the transactions between the User and Company on the Platform using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing a payment facility, We are neither acting as trustees nor acting in any fiduciary capacity with respect to the payments made by the User against the purchase/subscription of the Programs made available on the Platform.
          </p>

          <p>4. INTELLECTUAL PROPERTY RIGHTS</p>

          <p>4.1. Copyright</p>

          <p>
            4.1.1. All content included on the Platform, social media accounts of the Company are delivered to the Users as part of the Service offering, including but not limited to, text, graphics, logos, designs, photographs, button icons, images, audio/video clips, digital downloads, data compilations, software, recipes, workout programs (“Content”) is and shall be the property of the Company, and is protected by the applicable intellectual property laws. The compilation of all content on the Platform is the exclusive property of the Company, and shall not be reproduced or used without express written permission from the Company either by You or by any third party. You agree not to decompile, reverse engineer or disassemble any software or other products or processes accessible through the Platform, not to insert any code or product or manipulate the content of the Platform in any way that affects the user's experience, and not to use any data mining, data gathering or extraction method. We reserve the right to terminate your subscription/registration hereunder if We, in Our sole and absolute discretion, believe that You are in violation of this Clause.
          </p>

          <p>
            4.1.2. You hereby agree and acknowledge that the provision of Services through the Platform is solely for Your personal and non-commercial use.
          </p>

          <p>
            4.2. Trademarks**www.consultcraftinc.com** is the domain name registered by the Company. The Platform, including, but not limited to its graphics, logos, page headers, button icons, scripts and service names constitute trade dress of the Company. The trademarks, domain names, application name and trade dress in and to the Platform shall be the sole and exclusive property of the Company and the same shall not be used or reproduced without prior written approval from the Company, and may not be used in connection with any product or service that is not affiliated with the Company in any manner that is likely to: (a) cause confusion among other users; or (b) dilute the rights of the Company, or (c) to disparage or discredit the Company.
          </p>

          <p>5. ACCESS AND USAGE OF YOUR IMAGES</p>

          <p>
            5.1 We may either offer the opportunity to get Your photograph clicked or request You to share Your photographs (either single photo or in a group with other users) or appear in a video during a class/session (“Images”). The Images shall be clicked or recorded by the Company personnel or any individual authorised by the Company. Once an Image is uploaded on the Platform or on any of the Company’s social media handles, You may be allowed to tag Yourself in the Image. You acknowledge that the Images uploaded by the Company shall be accessible to all the Users/subscribers/followers of the Platform and/or the Company social media handles. The said Users may download or take a screenshot of the Images. You may also be allowed to upload Your photos or videos on Your social media handles or on such other Platform as you may deem fit and necessary. The Images may also be seen, accessed, or downloaded through third-party services such as search engines, APIs, websites and other services. The Company disclaims any and all liabilities with respect to the misuse, loss, modification, unavailability of the Images or content available on its Platform and/or on its social media handles.
          </p>

          <p>
            5.2 Ownership Rights: You agree and confirm that You shall provide/upload only those content/information/Images that You have the right to share and upload. You agree to only provide content or information that does not violate the law nor anyone’s rights (including intellectual property rights). All rights, title and interest including all intellectual property rights in the Content, any derivatives, modifications, enhancements and new inventions undertaken the Company shall belong to and vest entirely with the Company. The Company, in its sole discretion, may from time to time make additions to, deletions from, or modifications to its Platform, specifications and/or communications facilities, including to comply with changes, or contemplated changes, in law. For the information or content that You submit to the Company, You are hereby granting the Company and its affiliates a worldwide, transferable, non-exclusive and sublicensable right to use, copy, modify, distribute, publish and process, create derivative work, and such other right including displaying the said content on public platform including social media platform without any consent, notice and/or compensation to you or any third party. The Company reserves all the right, title and interest to its Platform not expressly granted to the fullest extent possible under applicable laws. Unless stated otherwise, all content uploaded by the Company is believed to be in the public domain as either promotional materials or publicity photos as the Company may determine. The Company shall have the right to review, screen, and delete any content that You may have submitted, if the Company thinks that Your content violates these Terms of Use and/or any third-party intellectual property rights.
          </p>

          <p>
            5.3 The Company may request You to share your personal experience of using the Platform and the results achieved by You to publish on the Platform. You understand that the testimonials are individual experiences, reflecting experiences of those who have used the Services in some way or another. However, these are individual results and results vary from person to person. You hereby provide your express consent and approval to the Company to use Your testimonial and/or any images/videos of Yours showing the results of the Company program, in a manner as deemed appropriate by the Company. The display of testimonials shall be at the sole discretion of the Company. The testimonials displayed are given verbatim except for grammatical or typing error corrections. Some testimonials may have been edited for clarity, or shortened in cases where the original testimonial included extraneous information of no relevance to the general public. Testimonials may be reviewed for authenticity before they are posted for public viewing.
          </p>

          <p>6. CONFIDENTIAL INFORMATION</p>

          <p>
            6.1. You agree to safeguard any Confidential Information as defined below, which You may have had access to during Your use of Our Services, and to prevent the unauthorized, negligent or inadvertent use or disclosure thereof. You will not, without Our prior written approval, directly or indirectly, use or disclose the Confidential Information to any person or business.
          </p>

          <p>
            6.2. In the event of violation of the above Clause by You, We will have the right to: (a) equitable and injunctive relief to prevent such prohibited use or disclosure, and (b) recover the amount of all damages in connection with such prohibited use or disclosure.
          </p>

          <p>
            6.3. For the purpose of these Terms of Use, “Confidential Information” means any information/content provided or made available to You in connection with use of the Platform and/or Services, including but not limited to the Company’s social media handles designs, concepts, processes, materials, communications, text, graphics, links, electronic art, animations, illustrations, artwork, audio clips, video clips, photos, images, and other data or copyrightable materials, trade secrets and the technology underlying the Services.
          </p>

          <p>7. FRAUD AND IMPROPER CONDUCT</p>

          <p>
            7.1. You may only access the Platform and use the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to Your use of the Services. You agree that You shall not in any way:
          </p>

          <p>(i) interfere with the ability of others to access or use the Services;</p>
          <p>(ii) disrupt the normal flow of communication or otherwise act in a manner that adversely affects other users' ability to use the Platform or the Services;</p>
          <p>(iii) hack into another user’s account or create a fake account using the name of another user;</p>
          <p>(iv) conduct in any way that would amount to sexual harassment under the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013;</p>
          <p>(v) stalk any user or any of the Company’s personnel (which includes trainers, coaches etc.) via internet, email, social media platforms, any other form of electronic communication, any form of physical stalking or any other form of sexual harassment which is not included in point (iv) above;</p>
          <p>(vi) interfere with or disrupt the Services or servers or networks connected to the Services, or disobey any requirements, procedures, policies, or regulations of networks connected to the Services;</p>
          <p>(vii) abuse the Company personnel (which includes trainers, coaches etc.) while providing training, subject him/her to any kind of sexual harassment, use obscenities while communicating with such Company personnel, make threats, solicit any personal information from any of the Company personnel or discuss matters other than those directly related to the Services that are being availed from the Platform;</p>
          <p>(viii) violate the terms and conditions stipulated in this Terms of Use document;</p>
          <p>(ix) make commercial use of the Platform that is designed to monetize the login process, the collection and use of any personal information provided by other users, or access to the Platform Content;</p>
          <p>(x) harass or advocate harassment of another person;</p>
          <p>(xi) transmit “junk mail”, “chain letters”, or unsolicited mass mailing or “spamming”;</p>
          <p>(xii) promote information that you know is false, misleading, or promotes illegal activities or conduct;</p>
          <p>(xiii) interfere with or disrupt the Platform or any server or network involved with the operation of the Platform;</p>
          <p>(xiv) collect or harvest from the Platform the names of other users for the purpose of transmitting to those other users unsolicited commercial messages;</p>
          <p>(xv) access or attempt to access any portion of the Platform or the Platform Content by any means other than through the Platform or use automated tools to operate the Platform (i.e., scripts, robots, etc.);</p>
          <p>(xvi) resell, rent, loan, or sublicense the Platform or Platform Content;</p>
          <p>(xvii) otherwise violates any local, national or other applicable law or regulation.</p>

          <p>
            7.2. You agree that You shall not use the Platform to host, display, upload, modify, publish, transmit, update or share any information that:
          </p>

          <p>(i) belongs to another person and to which You do not have any right to;</p>
          <p>(ii) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;</p>
          <p>(iii) harms other Users of the Platform in any way;</p>
          <p>(iv) fraudulently or dishonestly make use of electronic signature, password or any other unique identification feature of any other person who uses the Platform;</p>
          <p>(v) infringes any patent, trademark, copyright or other proprietary rights;</p>
          <p>(vi) violates any law for the time being in force;</p>
          <p>(vii) deceives or misleads the addressee about the origin of such messages; (viii) communicates any information which is grossly offensive or menacing in nature;</p>
          <p>(ix) impersonates another person;</p>
          <p>(x) contains software viruses or any other computer code, files or programs;</p>
          <p>(xi) is designed to interrupt, destroy or limit the functionality of any computer resource.</p>

          <p>
            If You become aware of any unauthorized use of the Platform or Platform Content, you must immediately notify us in writing at sc-support@consultcraftinc.com. In the event that the unauthorized use occurred through Your account by a third-party, You shall take all steps necessary to terminate such unauthorized use and cooperate with Us as may be reasonably requested to stop such unauthorized use.
          </p>

          <p>8. KEY POINTS TO BE BORNE IN MIND IN RELATION TO THE SERVICES OFFERED THROUGH THE PLATFORM</p>

          <p>
            8.1 This Platform shall contain content on personal fitness, nutrition, wellbeing, and dieting. Please note that such content made available on the Platform is not a substitute for direct, personal, professional medical care and diagnosis. None of the meal plans or exercise programs provided on the Platform should be performed or otherwise used/consumed without clearance from Your physician/doctor or health care provider first. The information provided on the Platform is not intended to provide specific physical or mental health advice, or any other advice whatsoever, for any User and should not be relied upon in that regard. We are not medical professionals and nothing on the Platform should be misconstrued to mean otherwise.
          </p>

          <p>
            8.2 Not all exercises shown on the Platform are suitable or appropriate for everyone. As with any exercise program, if at any point during Your workout You begin to feel dizzy, faint or have physical discomfort, You should stop immediately. You are solely responsible for exercising within Your limits and seeking medical advice and attention as appropriate. We are not responsible for any injuries that result from participating in the exercises shown on the Platform.
          </p>

          <p>
            8.3 We make no claims of curing any of your illness/weakness or achieving Your desired goals. Our only intention is to deliver the subscribed Services to the best of Our capability and ensure that each of the subscribed Services are rendered, unless our engagement is terminated. We do not guarantee any specific results from taking our programs. Due to different dispositions, the practices and treatments shared on the Platform varies for everyone. Many factors influence how successful the Users will be with Our recommendations. Any projections made in Our advertising materials are purely based on opinions, not facts.
          </p>

          <p>
            8.4 There may be risks associated with participating in activities presented on the Platform for people in good or poor health or with pre-existing physical or mental health conditions. If you choose to participate in these risks, you do so of your own free will and accord, knowingly and voluntarily assuming all risks associated with such activities.
          </p>

          <p>
            8.5 The results obtained from the information available on the Platform may vary, and will be based on your individual background, physical health, previous experience, capacity, ability to act, motivation and other variables. There are no guarantees concerning the level of success You may achieve/experience by subscribing to the program.
          </p>

          <p>9. LIMITATIONS AND DISCLAIMER OF WARRANTY</p>

          <p>
            9.1. The Platform, the Services and each portion thereof are provided "as is" without warranties of any kind either express or implied. To the fullest extent possible pursuant to applicable laws of India, We disclaim all warranties, express or implied, with respect to the Platform, the Services and each portion thereof, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or other violation of rights. Without limiting the foregoing, the Company makes no warranty that: (i) the Platform or the Services or the Content will meet Your requirements or Your use of the Platform or the Services will be uninterrupted, timely, secure or error-free; (ii) the results that may be obtained from the use of the Platform, or Services will be effective, accurate or reliable; (iii) the quality of the Platform or Services or Content will meet Your expectations; or (iv) any errors or defects in the Platform or Services or Content will be corrected. No advice or information, whether oral or written, obtained by You from the Company or through use of the Services shall create any warranty not expressly stated in the Terms of Use.
          </p>

          <p>
            9.2. The Company will have no liability related to any User Content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws. The Company also disclaims all liability with respect to the misuse, loss, modification or unavailability of any User Content.
          </p>

          <p>
            9.3. We do not warrant or make any representations regarding the use, validity, accuracy, or reliability of, or the results of the use of, or otherwise with respect to the Platform, the Services, the training rendered by the Company personnel and each portion thereof.
          </p>

          <p>
            9.4. The Company shall not be liable for any loss that You may incur as a consequence of unauthorized use of Your account or account information in connection with the Platform or Services made available through the Platform, either with or without your knowledge.
          </p>

          <p>
            9.5. Due to the digital nature of the program(s) offered on the Platform, We do not offer refunds for those who do not do their due diligence to ensure any of Our program(s) is the right fit for them. It is the User's responsibility to review this Terms of Use document carefully prior to purchase, use or access to any of Our Services. Please note, We do not offer refunds for Our programs and our exclusive bonuses and course extensions are non-refundable under any circumstances.
          </p>

          <p>
            9.6. Under no circumstances, including, but not limited to, negligence, shall We be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use the Platform, the Services or any portion thereof, even if We or Our authorized representative has been advised of the possibility of such damages.
          </p>

          <p>
            9.7. The Company has endeavored to ensure that all information on the Platform is correct, but the Company neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information, or the Services rendered through the Platform. The Company shall not be responsible for the delay or inability to use the Platform or related functionalities, the provision of or failure to provide functionalities, or for any information, software, functionalities and related graphics obtained through the Platform, or otherwise arising out of the use of the Platform, whether based on contract, tort, negligence, strict liability or otherwise. Further, the Company shall not be held responsible for non-availability of the Platform during periodic maintenance operations or any unplanned suspension of access to the Platform that may occur due to technical reasons or for any reason beyond the Company's control. You understand and agree that any material or data or Content downloaded or otherwise obtained through the Platform is done entirely at Your own discretion and risk, and that You will be solely responsible for any damage to Your computer systems or loss of data that results from the download of such material or data.
          </p>

          <p>
            9.8. During Your Use of the Platform, You may come across promotional activities including advertisements from third-parties for their good or services. Any agreement, correspondence, promotion, purchase between You or such third party, will be a separate agreement between You and such third party. The Company shall have no responsibility, liability, obligation for any such agreement, correspondence, purchase or promotion between You and any such third party and You shall be governed by the terms of use and privacy policy of such third party.
          </p>

          <p>
            9.9. The information available on the Platform including the social media accounts of the Company is for general health information only and is not intended to be a substitute for professional medical advice, diagnosis or treatment. We recommend that you consult a specialist doctor and not rely exclusively on information provided on the Website and/or the Company’s social media handles for your health needs. All specific medical questions should be presented to Your own health care provider and you should seek medical advice regarding Your health and before starting any nutrition, weight loss or any other type of workout program.
          </p>

          <p>
            9.10. You acknowledge and agree that there are obvious risks in undertaking fitness and exercise routines and programs and that whilst taking part in the programs or accessing or using any fitness products, including participating in any seminar or personal or group fitness activity organized by the Company, You may be at risk of personal injury including broken bones, soft tissue injuries (including injuries to muscles, tendons, ligaments, fascia (connective tissue), nerves, fibrous tissue and blood vessels), joint injuries, heart, lung and breathing problems (and aggravating a pre-existing condition or injury) due to:
          </p>

          <p>(a) known or unknown health problems or previous injuries;</p>
          <p>(b) pregnancy;</p>
          <p>(c) engaging in activity which is too strenuous for your level of fitness and health;</p>
          <p>(d) tripping or slipping – including over fitness equipment both at home and in a gym; and</p>
          <p>(e) attempting an activity which is beyond your exercise capability.</p>

          <p>10. INDEMNIFICATION</p>

          <p>
            10.1. You agree to indemnify, defend and hold harmless the Company, and our affiliates, officers, directors, agents, partners, employees, licensors, representatives and third party service providers or vendors (including our affiliates' respective officers, directors, agents, partners, employees, licensors, representatives, and third party providers) (“Indemnitees”), from and against all losses, expenses, damages, costs, claims and demands, including reasonable attorney's fees and related costs and expenses, due to or arising out of any content you submit, post to, email, or otherwise transmit to Us or through the Services/Platform, Your use of the Services/Platform, or any portion thereof, Your connection to the Services, or Your breach of these Terms of Use. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by You, and in such case, You agree to fully cooperate with such defense and in asserting any available defenses.
          </p>

          <p>
            10.2. In no event shall the Indemnitees be liable to You or any third-party for any special, incidental, indirect, consequential or punitive damages whatsoever, arising out of or in connection with Your use of or access to the Platform, the Services made available through the Platform or Content on the Platform. The limitations and exclusions in this Clause 10 shall apply to the maximum extent permitted by applicable laws.
          </p>

          <p>
            10.3. In addition, and without limiting the foregoing, to the fullest extent permitted by applicable law, in no event will Indemnitees aggregate liability arising out of or in connection with these Terms of User or the services rendered hereunder, whether in contract, tort (including negligence, product liability, or other theory), warranty, or otherwise, exceed the amount of actual fees charged from You.
          </p>

          <p>
            10.4. If applicable law does not permit the exclusion of certain warranties or the limitation or exclusion of liability, the scope and duration of such warranty exclusions and the extent of the liability of the Company shall be the minimum permitted under applicable law.
          </p>

          <p>11. TERMINATION</p>

          <p>
            11.1. We may terminate these Terms of Use by providing You with notice of such termination, which shall be effective immediately upon delivery of such notice to You. We may terminate these Terms of Use immediately without notice in the event of any breach by You of these Terms of Use or any of our applicable policies, as posted on the Platform from time to time.
          </p>

          <p>
            11.2. We may terminate these Terms of Use without notice to You by terminating your rights to use the Platform or the Services for any reason or no reason. In the event of termination or expiration of these Terms of Use, the following sections of these Terms of Use shall survive: (i) all provisions regarding ownership of intellectual property rights, Content and images; (ii) indemnification; (iii) disclaimer of warranties; and (iv) limitations of liability; (v) Consequences of improper conduct, fraud or abuse, and the provisions of this section.
          </p>

          <p>
            11.3. You agree that upon the termination of these Terms of Use, We may delete all information related to You on the Services and may bar Your access to the Platform and use of the Services.
          </p>

          <p>12. ASSIGNMENT</p>

          <p>
            This Terms of Use agreement may be assigned by the Company to any of its affiliates, group companies, partners or such other third parties without being required to: (i) intimate the Users of such assignment; and (ii) obtain a prior consent from the Users. The Users hereby agree and acknowledge that upon such assignment, the permitted assignee i.e., the Company’s affiliate or partner or such other third party (as the case may be) shall assume all obligations of the Company under this Terms of Use agreement, and the Company shall be relieved of its responsibilities or obligations from the effective date of such assignment.
          </p>

          <p>13. SEVERABILITY</p>

          <p>
            If any part of the Terms of Use for Services are determined to be invalid or unenforceable pursuant to applicable laws of India, including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed to be superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of the Terms of Use for Services shall continue in effect.
          </p>

          <p>14. NOTICES</p>

          <p>
            All notices from the Company will be served by email to Your registered email address or by general notification on the Platform. Any notice provided to the Company pursuant to the Terms of Use should be sent to sc-support@consultcraftinc.com.
          </p>

          <p>15. GENERAL</p>

          <p>
            Unless otherwise specified herein, this Terms of Use for Services constitutes the entire agreement between You and the Company in respect of the Services and supersedes all previous written and oral agreements between you and the Company, if any. The Company’s failure to act with respect to a breach committed by You or others does not waive its right to act with respect to subsequent or similar breaches.
          </p>

          <p>16. GOVERNING LAW</p>

          <p>
            16.1 This Terms of Use document shall be governed by and constructed in accordance with the applicable laws of the State of Delaware, USA without reference to conflict of laws principles. Any disputes arising or reliefs sought in relation to, or under, this Terms of Use and the Privacy Policy, shall be subject to the exclusive jurisdiction of the courts of Delaware, USA.
          </p>

          <p>17. GRIEVANCE OFFICER</p>

          <p>
            The name and contact details of the Grievance Officer are provided below:
          </p>

          <p>
            Anubhav Prasad - anubhavprasad@consultcraftinc.com
          </p>
      </div>

      {/* Scroll-to-Top Button */}
      <button
        type="button"
        aria-label="Scroll to top"
        onClick={scrollToTop}
        className={`fixed bottom-5 right-5 rounded-full shadow-lg border border-neutral-200 bg-white/90 backdrop-blur px-4 py-3 text-sm font-medium transition-opacity ${
          showScrollTop ? "opacity-100" : "opacity-0 pointer-events-none"
        }`}
      >
        ↑
      </button>

      {/* Footer */}
      <footer className="mx-auto max-w-5xl px-4 py-12 text-xs text-neutral-400">
        <div className="border-t border-neutral-200 pt-6">
          <p>End of document.</p>
        </div>
      </footer>
    </div>
  );
}
